@startuml
class McOption {
    + Init() : void
    + Save() : void
}
MonoBehaviour <|-- McOption
McOption --> "videos" McVideos
McOption --> "controls" McControls
McOption --> "sounds" McSounds
@enduml
