@startuml Prototype App Base System

class Param
{
    + {static} int msg
    + {static} float floP
    + {static} string strP

    + {static} void Init()
}

enum VOXEL_ID
{

}

Constants *-- VOXEL_ID
class Constants
{
    + {static} readonly int SPECIFIED_FPS = 60

    + {static} readonly int MSG_NULL = 0
    + {static} readonly int MSG_SUCSESS = 1
    + {static} readonly int MSG_FAILED = 2
    + {static} readonly int MSG_ERROR = 3
    + {static} readonly int MSG_WARNING = 4
    + {static} readonly int MSG_CHANGE_SCENE = 5

    + {static} readonly string SCENE_MENU = "Menu"
    + {static} readonly string SCENE_PLAY = "Play"

    + {static} readonly string TYPE_BACKGROUND = "background"
    + {static} readonly string TYPE_IMAGE = "image"
    + {static} readonly string TYPE_INPUT_BOX = "inputBox"
    + {static} readonly string TYPE_BUTTON = "button"
    + {static} readonly string TYPE_TEXT = "text"

    + {static} readonly string WND_MENU = "WindowMenu"

    + {static} readonly string VAXEL_STATE_NULL = "none"
    + {static} readonly string VAXEL_STATE_ITEM = "item"
    + {static} readonly string VAXEL_STATE_BLOCK = "block"
    + {static} readonly string VAXEL_STATE_ENTITY = "entity"

    + {static} readonly string VAXEL_TYPE_BUILD_BLOCK = "buildBlock"
    + {static} readonly string VAXEL_TYPE_GRASS = "grass"
    + {static} readonly string VAXEL_TYPE_ORE = "ore"
    + {static} readonly string VAXEL_TYPE_GLASS = "glass"
    + {static} readonly string VAXEL_TYPE_FENCE = "fence"
    + {static} readonly string VAXEL_TYPE_LEAF = "leaf"
    + {static} readonly string VAXEL_TYPE_SEED = "seed"
    + {static} readonly string VAXEL_TYPE_FLUID = "fluid"
    + {static} readonly string VAXEL_TYPE_FURNITURE = "furniture"
    + {static} readonly string VAXEL_TYPE_FALL = "fall"
    + {static} readonly string VAXEL_TYPE_FOOD = "food"
    + {static} readonly string VAXEL_TYPE_TOOL = "tool"
    + {static} readonly string VAXEL_TYPE_ARMOR = "armor"
    + {static} readonly string VAXEL_TYPE_ENCHANT_BOOK = "enchantBook"
    + {static} readonly string VAXEL_TYPE_ENTITY = "entity"
}

BaseManager *-- Param
BaseManager *-- Manager
class BaseManager
{
    - {static} PARAMS param
    - [SerializeField] Manager manager

    - void [Unity] Awake()
    - void [Unity] Start()
    - void [Unity] Update()
    - void Exit()

    - int SetFps()
    - int ChangeScene()
}

abstract class Element
{
    - [SerializeField] string type
    - [SerializeField] string elName

    + {abstract} void Init()
    + {abstract} void Show()
    + {abstract} void Close()
    + {abstract} void Execute()
    + {abstract} void Move(ref Vector2 vec, )
}

BackgroundEl --|> Element
class BackgroundEl
{
    + [override] void Init()
    + [override] void Show()
    + [override] void Close()   
    + [override] void Execute()
    + [override] void Move(ref Vector2 vec, )
}

ImageEl --|> Element
class ImageEl
{
    + [override] void Init()
    + [override] void Show()
    + [override] void Close()   
    + [override] void Execute()
    + [override] void Move(ref Vector2 vec, )
}

InputBoxEl --|> Element
class InputBoxEl
{
    + [override] void Init()
    + [override] void Show()
    + [override] void Close()   
    + [override] void Execute()
    + [override] void Move(ref Vector2 vec, )
}

ButtonEl --|> Element
class ButtonEl
{
    + [override] void Init()
    + [override] void Show()
    + [override] void Close()   
    + [override] void Execute()
    + [override] void Move(ref Vector2 vec, )
}

TextEl --|> Element
class TextEl
{
    + [override] void Init()
    + [override] void Show()
    + [override] void Close()   
    + [override] void Execute()
    + [override] void Move(ref Vector2 vec, )
}

GameWindow *-- Element
abstract class GameWindow
{
    - [SerializeField] string wndName

    - bool isCreated = false
    - bool isOpening = false
    - [SerializeField] bool isScroll = true
    - [SerializeField] bool isPopUp = false

    - [SerializeField] Canvas canvas
    - [SerializeField] Panel panel

    # [SerializeField] GameObject images
    # [SerializeField] GameObject texts

    - Dictionary<string, Element> diImageEl
    - Dictionary<string, Element> diTextEl

    + {abstract} void Init()
    + {abstract} void Show()
    + {abstract} void Close()
    + {abstract} void Execute()
}

MenuWindow *-- McOption
MenuWindow --|> GameWindow
class MenuWindow
{
    - McOption option

    - [SerializeField] GameObject backgrounds
    - [SerializeField] GameObject inputBoxes
    - [SerializeField] GameObject buttons

    - Dictionary<string, Element> diBackgroundEl
    - Dictionary<string, Element> diImageEl
    - Dictionary<string, Element> diInputBoxEl
    - Dictionary<string, Element> diButtonEl

    + [override] void Init()
    + [override] void Show()
    + [override] void Close()
    + [override] void Execute()
}

class McVideos
{

}

class McControls
{

}

class McSounds
{

}

McOption *-- McVideos
McOption *-- McControls
McOption *-- McSounds
class McOption
{

}

PlayWindow *-- World
PlayWindow --|> GameWindow
class PlayWindow
{
    + [override] void Init()
    + [override] void Show()
    + [override] void Close()
    + [override] void Execute()
}

Vaxel *-- VaxelData
class Vaxel
{
    [SerializeField] VaxelData data
}

abstract class VaxelData
{
    - [SerializeField] string name
    - [SerializeField] string state
    - [SerializeField] string type

    - [SerializeField] int id
    - [SerializeField] int maxCount

    - [SerializeField] bool isStackable
    - [SerializeField] bool isUsable
    - [SerializeField] bool isWearable

    - [SerializeField] Texture texture

    - bool isTargetting = false
    - bool isSelecting = false
    - bool isHolding = false
    - bool isWearing = false

    - Vector3 pos

    + {abstract} void Create()
    + {abstract} void Destroy()

    + void ItemGet(ref Player player)
    + void ItemDrop(ref Player player)
}

BuildBlockData --|> VaxelData
class BuildBlockData
{
    + [override] void Create()
    + [override] void Destroy()
}

GrassData --|> VaxelData
class GrassData
{
    + [override] void Create()
    + [override] void Destroy()
}

OreData --|> VaxelData
class OreData
{
    + [override] void Create()
    + [override] void Destroy()
}

GlassData --|> VaxelData
class GlassData
{
    + [override] void Create()
    + [override] void Destroy()
}

FenceData --|> VaxelData
class FenceData
{
    + [override] void Create()
    + [override] void Destroy()
}

LeafData --|> VaxelData
class LeafData
{
    + [override] void Create()
    + [override] void Destroy()
}

SeedData --|> VaxelData
class SeedData
{
    + [override] void Create()
    + [override] void Destroy()
}

FluidData --|> VaxelData
class FluidData
{
    + [override] void Create()
    + [override] void Destroy()
}

FurnitureData --|> VaxelData
class FurnitureData
{
    + [override] void Create()
    + [override] void Destroy()
}

FallData --|> VaxelData
class FallData
{
    + [override] void Create()
    + [override] void Destroy()
}

FoodData --|> VaxelData
class FoodData
{
    + [override] void Create()
    + [override] void Destroy()
}

ToolData --|> VaxelData
class ToolData
{
    + [override] void Create()
    + [override] void Destroy()
}

ArmorData --|> VaxelData
class ArmorData
{
    + [override] void Create()
    + [override] void Destroy()
}

EnchantBookData --|> VaxelData
class EnchantBookData
{
    + [override] void Create()
    + [override] void Destroy()
}

EntityData --|> VaxelData
class EntityData
{
    + [override] void Create()
    + [override] void Destroy()
}

class PlayerData
{

}

Player *-- PlayerData
class Player
{

}

class Blocks
{
    - List<Voxel> existingVoxel
}

class Entities
{
    - List<Voxel> existingVoxel
}

WorldData *-- Blocks
WorldData *-- Entities
WorldData *-- Vaxel
class WorldData
{
    - List<Voxel> voxels
    - Blocks[,,] blocks = new Blocks[size, height, size]
    - Entities[,,] entities = new Entities[size, height, size]

    + void SaveVaxels()
}

World *-- Player
World *-- WorldData
class World
{
    - int size = 513
    - int height = 320

    - [SerializeField] GameObject parentVaxelPrefabs
    - Dictionary<string, GameObject> vaxelPrefabs

    - Player player
    - WorldData data

    + void Load()
    + void UnLoad()

    + void Create()
    + void Save()
    + void Destroy()
}

Manager o-- GameWindow
abstract class Manager
{
    - [SerializeField] List<GameWindow> windows
    - Dictionary<string, int> windowNameToIndex

    # void Init()
    # void Destroy()

    # void ShowWindow(string name)
    # void CloseWindow(string name)

    # void ExecuteWindows()
    # void ScrollWindows()

    + {abstract} void BaseAwake()
    + {abstract} void BaseStart()
    + {abstract} void BaseUpdate()
    + {abstract} void BaseExit()
}

MenuManager --|> Manager
class MenuManager
{
    + [override] void BaseAwake()
    + [override] void BaseStart()
    + [override] void BaseUpdate()
    + [override] void BaseExit()
}

PlayManager --|> Manager
class PlayManager
{
    + [override] void BaseAwake()
    + [override] void BaseStart()
    + [override] void BaseUpdate()
    + [override] void BaseExit()
}


@enduml