@startuml Unity Minecraft World

enum VOXEL_STATE
{
    NONE,
    ITEM,
    BLOCK,
    USABLE,
    ENTITY
}

enum VOXEL_TYPE
{
    BUILD_BLOC
    ORE
    GLASS
    FENCE
    LEAF
    SEED
    FLUID
    FURNITURE
    FALL
    FOOD,
    TOOL,
    ARMOR,
    ENCHANT_BOOK
}

enum VOXEL_ID
{

}

class Entity
{

}

Mob --|> Entity
class Mob
{

}

class Inventory
{

}

Player *-- Inventory
Player --|> Entity
class Player
{

}

Voxel *-- VOXEL_STATE
Voxel *-- VOXEL_TYPE
Voxel *-- VOXEL_ID
abstract class Voxel
{
    - VOXEL_STATE state

    - [SerializeField] int maxStack
    - [SerializeField] bool isBlock

    - bool isHolding = false
    - bool isWearing = false
    - bool isSelecting = false

    - VOXEL_ID id
    - [SerializeField] VOXEL_TYPE type
    - [SerializeField] string name
    - [SerializeField] Texture texture

    + {abstract} void Create()
    + {abstract} void Destroy()

    + VOXEL_ID ItemGet(ref Player player)
    + VOXEL_ID ItemDrop(ref Player player)

    + VOXEL_ID ItemHold()
    + [virtual] VOXEL_ID ItemUse()
    + VOXEL_ID ItemDisHold()

    + VOXEL_ID ItemSelect(ref Inventory invent)
    + VOXEL_ID ItemPut(ref Inventory invent)
}

Block --|> Voxel
abstract class Block
{
    - bool isTarget = false

    + {abstract} void Place();
    + {abstract} void Break();

    + void Target()
    + [virtual] void Use()
    + void DeTarget()
}

Usable --|> Voxel
abstract class Usable
{
    + [override] VOXEL_ID ItemUse()
}

Wearable --|> Voxel
abstract class Wearable
{

}

class World
{
    - int size = 513
    - int height = 320

    - [SerializeField] GameObject parentVaxelPrefabs
    - Dictionary<string, GameObject> vaxelPrefabs

    - WorldData data

    + void Load()
    + void UnLoad()

    + void Create()
    + void Save()
    + void Destroy()

}


@enduml
